"""Create tables instance and responses

Revision ID: 1124f8ec138c
Revises: d881c8fd7ce6
Create Date: 2023-01-30 14:14:25.261702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1124f8ec138c'
down_revision = 'd881c8fd7ce6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_template_id', sa.String(length=36), nullable=True),
    sa.Column('coordinates', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_instances_id'), 'form_instances', ['id'], unique=False)
    op.create_table('form_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_instance_id', sa.String(length=36), nullable=True),
    sa.Column('form_item_id', sa.String(length=36), nullable=True),
    sa.Column('answer', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['form_instance_id'], ['form_instances.id'], ),
    sa.ForeignKeyConstraint(['form_item_id'], ['form_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_responses_id'), 'form_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_responses_id'), table_name='form_responses')
    op.drop_table('form_responses')
    op.drop_index(op.f('ix_form_instances_id'), table_name='form_instances')
    op.drop_table('form_instances')
    # ### end Alembic commands ###
