"""Tables Creation

Revision ID: 34e1c6d83fe4
Revises: 
Create Date: 2023-02-01 04:45:28.349385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e1c6d83fe4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_templates_id'), 'form_templates', ['id'], unique=False)
    op.create_table('form_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_template_id', sa.String(length=36), nullable=True),
    sa.Column('coordinates', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_instances_id'), 'form_instances', ['id'], unique=False)
    op.create_table('form_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_template_id', sa.String(length=36), nullable=True),
    sa.Column('index', sa.String(length=15), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('label', sa.String(length=250), nullable=True),
    sa.Column('input_type', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_items_id'), 'form_items', ['id'], unique=False)
    op.create_table('entry_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_item_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=250), nullable=True),
    sa.Column('value', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_item_id'], ['form_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_options_id'), 'entry_options', ['id'], unique=False)
    op.create_table('form_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.String(length=15), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('label', sa.String(length=250), nullable=True),
    sa.Column('input_type', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('form_instance_id', sa.String(length=36), nullable=True),
    sa.Column('form_item_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['form_instance_id'], ['form_instances.id'], ),
    sa.ForeignKeyConstraint(['form_item_id'], ['form_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_responses_id'), 'form_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_responses_id'), table_name='form_responses')
    op.drop_table('form_responses')
    op.drop_index(op.f('ix_entry_options_id'), table_name='entry_options')
    op.drop_table('entry_options')
    op.drop_index(op.f('ix_form_items_id'), table_name='form_items')
    op.drop_table('form_items')
    op.drop_index(op.f('ix_form_instances_id'), table_name='form_instances')
    op.drop_table('form_instances')
    op.drop_index(op.f('ix_form_templates_id'), table_name='form_templates')
    op.drop_table('form_templates')
    # ### end Alembic commands ###
