"""check

Revision ID: 73b303c0d1ca
Revises: 1124f8ec138c
Create Date: 2023-01-30 23:52:26.245613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b303c0d1ca'
down_revision = '1124f8ec138c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
