"""add form instances 2 and form responses 2

Revision ID: a1a400288cd6
Revises: 73b303c0d1ca
Create Date: 2023-01-31 23:38:12.245348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a400288cd6'
down_revision = '73b303c0d1ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_instances_2',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_template_id', sa.String(length=36), nullable=True),
    sa.Column('coordinates', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_instances_2_id'), 'form_instances_2', ['id'], unique=False)
    op.create_table('form_responses_2',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.String(length=15), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('label', sa.String(length=250), nullable=True),
    sa.Column('input_type', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('form_instance_id', sa.String(length=36), nullable=True),
    sa.Column('form_item_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['form_instance_id'], ['form_instances_2.id'], ),
    sa.ForeignKeyConstraint(['form_item_id'], ['form_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_responses_2_id'), 'form_responses_2', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_responses_2_id'), table_name='form_responses_2')
    op.drop_table('form_responses_2')
    op.drop_index(op.f('ix_form_instances_2_id'), table_name='form_instances_2')
    op.drop_table('form_instances_2')
    # ### end Alembic commands ###
