"""add creation date to options table

Revision ID: d881c8fd7ce6
Revises: e1ac79d7732c
Create Date: 2023-01-29 23:41:43.105522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd881c8fd7ce6'
down_revision = 'e1ac79d7732c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_options', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('entry_options', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry_options', 'created_at')
    op.drop_column('entry_options', 'is_active')
    # ### end Alembic commands ###
